### ISSUE TITLE
node: 14.16.1 and yarn: 1.22.10 -> I into this problem, how should I fix it?  Error: Cannot find module './runtime/providers/log'   

### ISSUE THREAD

**Issue by NitichaiSawangsai** [nuxt-community/web-vitals-module#29] opened 2021-08-14 09:01 UTC
```
 WARN  Module @nuxtjs/web-vitals not found. Please ensure @nuxtjs/web-vitals is in devDependencies and installed. HINT: During build step, for npm/yarn, NODE_ENV=production or --production should NOT be used.


 FATAL  Cannot find module './runtime/providers/log'                              15:57:32
Require stack:
- /node_modules/@nuxtjs/web-vitals/dist/index.cjs
- /node_modules/@nuxt/core/dist/core.js

  Require stack:
  - node_modules/@nuxtjs/web-vitals/dist/index.cjs
  - node_modules/@nuxt/core/dist/core.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
  at Function.a [as resolve] (node_modules/jiti/dist/v8cache.js:2:2508)
  at Object.<anonymous> (node_modules/@nuxtjs/web-vitals/dist/index.cjs:13:22)
  at Module.o._compile (node_modules/jiti/dist/v8cache.js:2:2778)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Module.require (internal/modules/cjs/loader.js:952:19)
  at require (internal/modules/cjs/helpers.js:88:18)
  at Resolver.f [as _require] (node_modules/jiti/dist/jiti.js:1:53846)

```

@nuxtjs/web-vitals 0.1.7

**Comment by ddosdor** [comment] 2021-08-14 09:10
I have had a similar problem since the day before yesterday -> #28

**Comment by victorgarciaesgi** [comment] 2021-08-16 12:45
Getting this error two since 2 days with Vercel :(

**Comment by hojas** [comment] 2021-08-17 03:44
+1

**Comment by mahnouel** [comment] 2021-08-17 14:26
did anyone find a solution yet?

**Comment by victorgarciaesgi** [comment] 2021-08-17 14:32
I decreased the version to `0.1.4` and it worked

**Comment by danielroe** [comment] 2021-08-23 14:22
closing as a duplicate of #28

**Closed by danielroe** 2021-08-23 14:22 UTC
